name: unit-tests
on: pull_request
jobs:
  build:
    runs-on: fedora-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        # TODO: run

      - name: Test
        # TODO: run